import { Indie_Flower } from 'next/font/google';
import "./globals.css";
// import { Geist, Geist_Mono } from "next/font/google";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 1. Define the font loader. Specify the weight used (Indie Flower is usually 400).
const indieFlower = Indie_Flower({
  weight: '400',
  subsets: ['latin'],
  // 2. Define a CSS variable name. This makes it easy to use in Tailwind CSS.
  variable: '--font-indie-flower', 
});

import { ReactNode } from "react";

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${indieFlower.className} ${indieFlower.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
